language: go
go:
- '1.3'
env:
- CGO_ENABLED=0
before_install:
- cp ci/travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
- $HOME/travis-ci.sh before-install
install:
- $HOME/travis-ci.sh install
before_script:
- $HOME/travis-ci.sh before-script
script:
- $HOME/travis-ci.sh script
after_script:
- $HOME/travis-ci.sh after-script
after_success:
- $HOME/travis-ci.sh after-success
before_deploy:
- $HOME/travis-ci.sh before-deploy
- cd built
after_deploy:
- $HOME/travis-ci.sh after-deploy
notifications:
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalamuna.com
    - ben@kalamuna.com
    on_success: always
deploy:
  provider: releases
  api_key:
    secure: IBRowapAs054LC/zBYzhQMBM/h8w1qrySdzQcs7F5Kgn6gdGEfGrBnbdJpHQ66JwPewBy6O76My/TMxYzOIqD9osRF3/TAn/PSyKEjGPgJrVwY8PO56XMuHNyLsq6iv9KLpAEXmXQmdvFNNlnfYdhVUXTCgKgJ0Xx49gBqesCYo=
  file:
  - skydns
  - skydnsctl
  on:
    repo: kalabox/skydns1
    all_branches: true
    tags: true
  skip_cleanup: true
